### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module on Nextjs 13.5.6

### ISSUE THREAD

**Issue by teukurijal** [pushy/pushy-sdk-web#13]
```
/node_modules/pushy-sdk-web/src/lib/pushy.js:4
import api from '../util/api';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)

```

"next": "13.5.6",
"pushy-sdk-web": "^1.0.18",

node v20.11.1

anyone know this issue, need help

**Comment by pushy** [comment]
Hi @teukurijal,
Thanks for reporting this issue. We'd be glad to assist.

We've just released version `1.0.19` of the Pushy Web SDK with a fix for this issue.

Please update by running the following command:
```
npm install pushy-sdk-web@latest --save
```

Then, rerun your code and let us know if the issue is indeed resolved.

**Comment by teukurijal** [comment]
hi @pushy, 

I have installed new version `1.0.19`

and update `service-worker.js` file
```
// Import Pushy Service Worker 1.0.19
importScripts('https://sdk.pushy.me/web/1.0.19/pushy-service-worker.js');
```

still not work and got new error 

![Screenshot 2024-04-26 at 14 17 17](https://github.com/pushy/pushy-sdk-web/assets/47308553/d261f61f-9307-497e-85ee-0012dbf3da29)

**Comment by pushy** [comment]
Hi @teukurijal,
Apologies for that!

We've just released version `20` of the Pushy Web SDK which fully adds support for Next.js. We've tested it out and it works perfectly.

Please update by running the following command:
```
npm install pushy-sdk-web@latest --save
```

Then, rerun your code and let us know if the issue is indeed resolved.

**Comment by pushy** [comment]
Hi @teukurijal,
Apologies for that!

We've just released version `1.0.21` of the Pushy Web SDK which fully adds support for Next.js. We've tested it out and it works perfectly.

Please update by running the following command:
```
npm install pushy-sdk-web@latest --save
```

Make sure to import and execute the `pushy-sdk-web` package inside `React.useEffect()` to avoid Next.js Server Side Rendering as follows:

```
import * as React from 'react';

React.useEffect(() => {
    async function exec() {
      // Import Pushy SDK
      const Pushy = (await import('pushy-sdk-web')).default

      // Register device
      Pushy.register({ appId: 'PUSHY_APP_ID' }).then(function (deviceToken) {
        // Print device token to console
        alert('Pushy device token: ' + deviceToken);

        // Send the token to your backend server via an HTTP GET request
        //fetch('https://your.api.hostname/register/device?token=' + deviceToken);

        // Succeeded, optionally do something to alert the user
      }).catch(function (err) {
        // Notify user of failure
        alert('Registration failed: ' + err.message);
      });
    }
    exec();
  }, []);

```

Then, rerun your code and let us know if the issue is indeed resolved.

**Comment by teukurijal** [comment]
it's work on nextjs 13.5.6, thanks a lot @pushy
